ddpg:
  train_env:
    normalize_action: False
  eval_env:
    normalize_action: False
  train:
    num_envs: 25
    total_timesteps: 10000000 
    save_interval: 250000
    eval_freq: 250000
    model_path: ./models/experiment3/ddpg
    checkpoint_prefix: ddpg_dualdevicenav_ckpt
    log_path: ./logs/experiment3/ddpg_dualdevicenav_eval.csv
    policy_kwargs:
      net_arch: [400, 300]
    learning_rate: 0.001
    action_noise:
      stddev: 0.1

td3:
  train_env:
    normalize_action: False
  eval_env:
    normalize_action: False
  train:
    num_envs: 25
    total_timesteps: 10000000
    save_interval: 250000
    eval_freq: 250000
    model_path: ./models/experiment3/td3
    checkpoint_prefix: td3_dualdevicenav_ckpt
    log_path: ./logs/experiment3/td3_dualdevicenav_eval.csv
    policy_kwargs:
      net_arch: [400, 300]
    learning_rate: 0.001
    action_noise:
      stddev: 0.1

sac:
  train_env:
    normalize_action: False
  eval_env:
    normalize_action: False
  train:
    num_envs: 25
    total_timesteps: 10000000
    save_interval: 250000
    eval_freq: 250000
    model_path: ./models/experiment3/sac
    checkpoint_prefix: sac_dualdevicenav_ckpt
    log_path: ./logs/experiment3/sac_dualdevicenav_eval.csv
    policy_kwargs:
      net_arch: [400, 300]
    learning_rate: 0.0003

ppo:
  train_env:
    normalize_action: True
  eval_env:
    normalize_action: True
  train:
    num_envs: 25
    total_timesteps: 10000000
    save_interval: 250000
    eval_freq: 250000
    model_path: ./models/experiment3/ppo
    checkpoint_prefix: ppo_dualdevicenav_ckpt
    log_path: ./logs/experiment3/ppo_dualdevicenav_eval.csv
    policy_kwargs:
      net_arch: [64, 64]
    learning_rate: 0.00056
